name: CI
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "9.0"
          - "9.2"
          - "9.4"
          - "9.6"
          - "9.8"
        include:
        - os: macOS-latest
          ghc: "9.8"
        - os: windows-latest
          ghc: "9.8"

    steps:

    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}

    - uses: actions/cache@v4
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}

    - name: Cabal version
      run: |
        cabal --version

    - name: Unpack
      run: |
        cabal sdist --ignore-project --output-directory ..
        cd ..
        cabal get radix-tree-*.tar.gz

    - name: Build & Test
      run: |
        cd ../radix-tree-*/
        cabal build all --enable-tests
        cabal test --enable-tests --test-show-details=direct all

    - name: Haddock
      run: |
        cd ../radix-tree-*/
        cabal haddock all

    - name: Cabal check
      run: |
        cd ../radix-tree-*/
        cabal check
